# Generated by Django 4.2.2 on 2023-06-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=2)),
                ('rate', models.IntegerField()),
                ('type', models.CharField(choices=[('film', 'film'), ('series', 'series'), ('anime film', 'anime film'), ('anime series', 'anime series')], max_length=64)),
            ],
        ),
    ]
