# Generated by Django 4.2.2 on 2023-07-01 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmsDb', '0002_alter_film_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.CharField(choices=[('film', 'film'), ('series', 'series'), ('anime film', 'anime_film'), ('anime series', 'anime_series')], max_length=64),
        ),
        migrations.CreateModel(
            name='PersonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmsDb.film')),
            ],
        ),
    ]
